routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::resource('/movie', 'Admin\MovieController');
Route::resource('/cast', 'Admin\CastController');
Route::resource('/peran', 'Admin\PeranController');
Route::resource('/film', 'MovieController');
Route::resource('/review', 'ReviewController');
Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
});

resources/views/admin/edit.blade.php
@extends('layouts.app')

@section('title')
    Upload Your Movie
@endsection

@section('content')

<div class="movie-detail mt-3">
    <div class="container">
        <h4>Upload Your Movie</h4>
        <form action="/movie/{{$film->id}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="judul">Movie Title</label>
                <input type="text" class="form-control" name="judul" id="judul" value=" {{$film->judul}}">
                @error('judul')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label>Description</label>
                <textarea name="ringkasan" id="ringkasan" class="form-control" rows="5" placeholder="{{$film->ringkasan}}" value="{{$film->ringkasan}}"></textarea>
                @error('ringkasan')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="title">Year</label>
                <input type="text" class="form-control" name="tahun" id="tahun" value="{{$film->tahun}}">
                @error('tahun')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleInputFile">Movies Poster</label>
                <div class="input-group">
                    <div class="custom-file">
                    <input type="file" name="poster" id="poster">
                    
                    @error('poster')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                    @enderror
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="exampleSelectBorder">Movies Genre</label>
                
                <select class="custom-select form-control-border" name="genre_id" id="genre_id" >
                    @foreach ($genre as $key=>$value)
                    @if ($value->id == $film->genre_id)
                    <option value="{{$value->id}}" selected>{{$value->nama}}</option>
                    @else
                    <option value="{{$value->id}}">{{$value->nama}}</option>
                    @endif
                    @endforeach
                </select>
                @error('genre_id')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>            
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>
    </div>
</div>

@endsection

resources/views/admin/home.blade.php
@extends('adminlte.master')

@section('content')
<main class="text-dark">
    <div class="main ">
        <div class="container">       
        <a href="{{route('movie.create')}}" class="btn btn-primary m-2" style="background-color: white; color: black">Tambah</a>    
        </div>
    </div>
    <div class="list mt-3">
        <div class="container">
            <h5>List Movies</h5>
            <div class="row d-flex justify-content-">
                @foreach ($film as $key=>$value)
                <div class="col-3">
                    <div class="card" >
                        <img src="images/{{$value->poster}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{$value->judul}}</h5> <br>
                            <h6>{{$value->genre->nama}}</h6>
                            <p class="card-text">{{$value->ringkasan}}</p>
                            <a href="/movie/{{$value->id}}/edit" class="btn btn-secondary">Edit</a>
                            <form action="/movie/{{$value->id}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <input type="submit" class="btn btn-secondary mt-1" value="Delete">
                            </form>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/admin/input-movie.blade.php
@extends('layouts.app')

@section('title')
    Upload Your Movie
@endsection

@section('content')

<div class="movie-detail mt-3">
    <div class="container">
        <h4>Upload Your Movie</h4>
        <form action="/movie" method="POST" enctype="multipart/form-data">
            @csrf
            
            <div class="form-group">
                <label for="judul">Movie Title</label>
                <input type="text" class="form-control" name="judul" id="judul" placeholder="Enter Your Movies Title">
                @error('judul')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label>Description</label>
                <textarea name="ringkasan" id="ringkasan" class="form-control" rows="5" placeholder="Enter ..."></textarea>
                @error('ringkasan')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="title">Year</label>
                <input type="text" class="form-control" name="tahun" id="tahun" placeholder="Enter Your Movie">
                @error('tahun')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <div class="form-group">
                <label for="exampleInputFile">Movies Poster</label>
                <div class="input-group">
                    <div class="custom-file">
                    <input type="file" name="poster" id="poster">
                    
                    @error('poster')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                    @enderror
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="exampleSelectBorder">Movies Genre</label>
                
                <select class="custom-select form-control-border" name="genre_id" id="genre_id" >
                    @foreach ($genre as $key=>$value)
                    <option value="{{$value->id}}">{{$value->nama}}</option>
                    @endforeach
                </select>
                @error('genre_id')
                    <div class="alert alert-danger">
                        {{ $message }}
                    </div>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Upload</button>
        </form>
    </div>
</div>

@endsection
@push('scripts')
    <script>
  var editor_config = {
    path_absolute : "/",
    selector: 'textarea.my-editor',
    relative_urls: false,
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table directionality",
      "emoticons template paste textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    file_picker_callback : function(callback, value, meta) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?editor=' + meta.fieldname;
      if (meta.filetype == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.openUrl({
        url : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no",
        onMessage: (api, message) => {
          callback(message.content);
        }
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endpush